#### Q. random.randint()를 사용하여 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])를 출력하세요.

In [132]:
import random
import numpy as np
a=np.random.randint(0,1,size=10)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Q. np.random.rand()를 이용해서 5개의 난수를 생성하고 형변환을 통해서 0보다 큰 정수로 출력하세요.

In [148]:
af = np.random.rand(1,5)*10
print(af)
ai = af.astype('int32')
print(ai)

[[1.0959861  8.53029654 7.3901706  1.98946975 7.57803481]]
[[1 8 7 1 7]]


#### Q. arange, zeros, ones를 이용해서 1차원 배열, 2차원 배열(3,3) 을 각각 생성하세요.

In [163]:
a = np.arange(9)
b = a.reshape(3,3)
print(a)
print(b,'\n')

azero = np.zeros((5), dtype='int32')
print(azero)
azero2 = np.zeros((3,3), dtype='int32')
print(azero2,'\n')

aone=np.ones((5), dtype='int32')
aone2=np.ones((3,3), dtype='int32')

print(aone)
print(aone2)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[1 1 1 1 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


#### Q. np.random.randint()를 활용 (4,3) 배열 mt1 을 생성하세요

In [169]:
a = np.random.randint(0,12,size=12)
print(a)
mt1=a.reshape(4,3)
print(mt1)

[ 8  3  5  3  7  3  7  4  3 10  4  4]
[[ 8  3  5]
 [ 3  7  3]
 [ 7  4  3]
 [10  4  4]]


#### Q. mt1을 2x6 행렬로 변환 mt2로 출력하세요.

In [170]:
mt2 = mt1.reshape(2,6)
print(mt2)

[[ 8  3  5  3  7  3]
 [ 7  4  3 10  4  4]]


#### Q. mt2를 1차원 배열로 변환 후 mt3로 출력하세요.

In [172]:
mt3 = mt2.reshape(1,-1)
print(mt3)

[[ 8  3  5  3  7  3  7  4  3 10  4  4]]


#### Q. arange() 함수를 이용해서  0 ~ 29 정수 배열을 생성하고 2 X 5 X 3 3차원 배열로 변환하세요. 

In [7]:
array1 = np.arange(30)
array3d = array1.reshape((2,5,3)) # 2, 5는 2행 5열이고 3은 깊이(겹)를 의미한다. (2행 5열 데이터가 3겹으로 존재)
print(array3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


#### Q. 1 ~ 12 연속된 정수 배열을 생성하고 2 X 3 X 2 3차원 배열로 변환 후 list로 출력하세요. 

In [9]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array23d=array2.reshape((2,3,2))
print(array2)
print(array23d)
print(array3d.tolist())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]], [[15, 16, 17], [18, 19, 20], [21, 22, 23], [24, 25, 26], [27, 28, 29]]]


#### Q. 0 ~ 29 연속 정수 배열을 생성하고 (10,3) 행렬로 변환 후 인덱싱으로 다음을 출력하세요.
- 12
- [24,25,26]
- 3번째 열 
- 2번째 ~ 5번째 행
- [10,13,16]

In [179]:
arr1 = np.arange(30)
array_1 = arr1.reshape(10,3)
print(array_1)      # array_1 출력
print(array_1[4,0]) #12 출력
print(array_1[-2])  #[24,25,26] 출력 : 뒤에서 2번째 꺼
print(array_1[2:6]) # 2~(6-1)번째 행 출력
print(array_1[3,1],array_1[4,1],array_1[5,1]) # 10 13 16 출력
print(array_1[3:6,1])# 10 13 16 출력
print(array_1[3:6,[1]]) # 2차원배열로 3행 1열로 출력 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
12
[24 25 26]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
10 13 16
[10 13 16]
[[10]
 [13]
 [16]]


#### Q. 5 ~ 20 연속 정수 배열을 생성하고 불린 인덱싱을 이용하여 짝수만 출력하세요.
#### Q. 동일 배열에서 12보다 큰 정수만 출력하세요.

In [116]:
a=np.arange(5,21)
b=a[(a%2==0)]
print(b)

[ 6  8 10 12 14 16 18 20]


In [117]:
c=a[(a>12)]
print(c)

[13 14 15 16 17 18 19 20]


#### Q. random.randint()를 이용해서 10개의 배열을 a1으로 생성후 정렬하세요(내림차순)

In [256]:
a=np.random.randint(0,10,size=10)
b=np.sort(a)[::-1]
print(b)

[9 9 9 8 7 5 5 2 1 0]


#### Q. 1 ~ 21 정수를 랜덤하게 (3,3) 행렬로 생성 후 row, column 방향으로 각각 정렬하세요.

In [233]:
a = np.random.randint(1,22,size=9)
b = a.reshape(3,3)
print(b)

[[20 10  6]
 [20  9  8]
 [ 1 19 12]]


#### Q. 10에서 20사이의 정수로 구성된 (5,3) 행열을 np.random을 이용해서 nmt1으로 생성하세요.

In [271]:
a = np.random.randint(10,20,size=15)
mt1 = a.reshape(5,3)
print(mt1)

[[19 19 13]
 [19 19 16]
 [12 16 18]
 [17 14 10]
 [10 10 15]]


#### Q. mt1 행렬을 전치 후 mt2로 출력하세요.

In [272]:
mt2 = mt1.T
print(mt2)

[[19 19 12 17 10]
 [19 19 16 14 10]
 [13 16 18 10 15]]


#### Q. 6개의 원소로 구성되는 배열을 np.random을 활용하여 생성 mt1으로 출력하세요.

In [277]:
a = np.random.randint(1,20,size=6)
mt1 = a.reshape(1,-1)
mt1

array([[18,  1, 12, 18, 12,  3]])

#### Q. 행벡터 mt를 전치하여 열벡터로 변환하세요.

In [279]:
mt2=mt1.T
mt2

array([[18],
       [ 1],
       [12],
       [18],
       [12],
       [ 3]])

#### Q. 배열 matrix를 broadcasting을 이용하여 다음 배열을 출력하는 연산을 수행하세요. 
array([[101, 202, 303],\
       [104, 205, 306],\
       [107, 208, 309]])


In [285]:
a = [100,200,300]
b = np.arange(start=1,stop=10)
c = b.reshape(3,3)
print(c,'\n')
print(a+c)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[101 202 303]
 [104 205 306]
 [107 208 309]]


#### Q. (3,3) 2차원 배열을 np.random으로 생성하여 mt1으로 저장하고 차원을 구하세요.

In [293]:
array = np.random.randint(1,100,size=9)
array2d = array.reshape(3,3)
print(array2d, '이 배열의 차원은 {}차원 입니다.'.format(array2d.ndim))

[[90 70 19]
 [87 11 16]
 [53 29  3]] 이 배열의 차원은 2차원 입니다.


#### Q. 아래 두개의 행렬에 대한 덧셈, 뺄셈, 곱셈을 수행하세요

In [308]:
mt1 = np.array([[1, 1, 2],
               [1, 1, 1],
               [3, 3, 4]])

mt2 = np.array([[7, 6, 8],
                [7, 7, 6],
                [8, 7, 8]])

In [310]:
msum = mt1+mt2
print(msum,'덧셈\n')
mmul = np.dot(mt1,mt2)
print(mmul,'곱셈\n')
mmin = mt1-mt2
print(mmin,'뺄셈')

[[ 8  7 10]
 [ 8  8  7]
 [11 10 12]] 덧셈

[[30 27 30]
 [22 20 22]
 [74 67 74]] 곱셈

[[-6 -5 -6]
 [-6 -6 -5]
 [-5 -4 -4]] 뺄셈


#### Q. 응용(종속변수, 예측모델 만들어보기)

In [359]:
#고객 구매데이터 생성(id, 성별, 연령, 지역, 상품, 가격, 구매시간)
import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')

a= np.random.randint(1,20, size=10) #1번에서 20번정도 구매하는 빈도가 생기는걸 정해줌(10개의 데이터)
sr_a = pd.Series(a, name='Freq')


b=np.random.choice(['KF94마스크','KF80마스크','N95마스크'],size=10)
sr_b=pd.Series(b,name='Prod')

c=np.random.choice(['롯데마트','코스트코','이마트'],size=10)
sr_c=pd.Series(c,name='Mart')

d=np.random.randint(1,1000,size=10)
sr_d=pd.Series(d,name='Amount')

e=np.random.choice(['Man','Woman'],size=10)
sr_e=pd.Series(e, name='Sex')

f=np.random.choice(['Seoul','Daejeon','Daegu','Busan','Changwon', 'Gangwon', 'Mokpo'],size=10)
sr_f=pd.Series(f, name='Region')

g=np.random.choice(range(1,15) ,size=10,replace=False)
sr_g=pd.Series(g, name='ID')

t=np.random.choice([datetime.datetime.now()],size=10)
sr_t=pd.Series(t, name='time')

hour = np.random.randint(1,180,size=10)
sr_hour = pd.Series(hour,name='머문시간(분)')

comparison = sr_d/sr_hour
sr_comp = pd.Series(comparison, name='분당판매량')

df=pd.concat([sr_a,sr_b,sr_c,sr_d,sr_e,sr_f,sr_g,sr_t,sr_hour,sr_comp],axis=1)
display(df)

x = 0
y = 0
z = 0

for i in range(10):
    if df['Mart'][i] == '이마트':
        x = x+1
    elif df['Mart'][i] =='롯데마트':
        y = y+1
    elif df['Mart'][i] =='코스트코':
        z = z+1
        

v = ['이마트','롯데마트','코스트코']
sr_v = pd.Series(v,name='Mart')

arr1 = np.array([x,y,z])
arr2=np.sort(arr1)[::-1] #내림차순 정렬
sr_arr1 = pd.Series(arr2,name='MartValue')

df2=pd.concat([sr_v,sr_arr1],axis=1)
df2
display(df2) #많이 팔린순으로 정렬

Freq     Prod  Mart  Amount    Sex    Region  ID  \
0     2  KF94마스크   이마트     916    Man   Daejeon   6   
1     4   N95마스크  롯데마트     357    Man     Mokpo  12   
2     3   N95마스크   이마트     808  Woman     Busan   2   
3     6  KF80마스크  롯데마트     692    Man     Busan  10   
4     9  KF94마스크   이마트     314  Woman     Mokpo   7   
5    15  KF94마스크   이마트     552  Woman   Gangwon   1   
6     7  KF94마스크   이마트     592  Woman     Mokpo   9   
7    12  KF94마스크  코스트코     823  Woman  Changwon   5   
8     9   N95마스크  코스트코     493  Woman     Seoul   8   
9     8   N95마스크  코스트코     910  Woman   Gangwon  11   

                        time  머문시간(분)      분당판매량  
0 2020-03-17 18:29:22.018939      143   6.405594  
1 2020-03-17 18:29:22.018939       88   4.056818  
2 2020-03-17 18:29:22.018939       56  14.428571  
3 2020-03-17 18:29:22.018939      150   4.613333  
4 2020-03-17 18:29:22.018939       92   3.413043  
5 2020-03-17 18:29:22.018939       85   6.494118  
6 2020-03-17 18:29:22.018939       11  53.818182  
7 2020-03-17 18:29:22.018939       53  15.528302  
8 2020-03-17 18:29:22.018939       17  29.000000  
9 2020-03-17 18:29:22.018939      131   6.946565

Mart  MartValue
0   이마트          5
1  롯데마트          3
2  코스트코          2