## 훈련과정 : R·파이썬 기반 빅데이터 분석 전문가 양성과정
- 교과목 평가 : 통계기반 데이터 분석
- 성명 : 호지수
- 점수 : 70 / 80 (3번, 7번 틀렸습니다.)

In [1]:
# df 생성
import pandas as pd
df = pd.read_csv('../auto-mpg.csv', header=None)
df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

#### Q1. df 데이터프레임에 대하여 아래 사항을 수행하세요. --- (15점)
1. 'mpg','cylinders','displacement','weight','acceleration','model year','origin','name' 컬럼의 통계요약표를 출력
2. mpg 컬럼의 평균값, 중간값, 최대값, 최소값, 표준편차 각각 개별 출력
3. mpg 컬럼과 weight컬럼간 상관계수 출력

In [2]:
df2 = df.drop(df.columns[[3,3]], axis=1, inplace=False)
display(df2.describe())
print('평균',df2.mpg.mean())
print('중간',df2.mpg.median())
print('최대',df2.mpg.max())
print('최소',df2.mpg.min())
print('표준편차',df2.mpg.std())
df3 = df2[['mpg','weight']]
display(df3.corr(),'mpg컬럼과 weight컬럼간 상관계수')

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

평균 23.514572864321607
중간 23.0
최대 46.6
최소 9.0
표준편차 7.815984312565782


mpg    weight
mpg     1.000000 -0.831741
weight -0.831741  1.000000

'mpg컬럼과 weight컬럼간 상관계수'

#### Q2. df.horsepower의 통계요약표를 출력하세요.  ----- (10점)

In [3]:
df['horsepower'].describe()

count       398
unique       94
top       150.0
freq         22
Name: horsepower, dtype: object

#### Q3. 아래 사항을 처리 하세요. --- (5점)  - 틀림
- df.origin 열의 고유값을 출력하세요.
- df.origin 열에 대하여 정수형 데이터를 문자형 데이터로 변환한 후 고유값을 출력하세요.

In [4]:
print('df.origin 고유값',df.origin.unique())
dfo = df.origin.astype('object')
print('df.origin열을 문자형 데이터로 변환한 후 고유값 출력',dfo.unique())

df.origin 고유값 [1 3 2]
df.origin열을 문자형 데이터로 변환한 후 고유값 출력 [1 3 2]


In [5]:
print((df.origin).dtype)
# origin 열의 고유값 확인
print(df['origin'].unique())

# 정수형 데이터를 문자형 데이터로 변환 
df['origin'].replace({1:'USA', 2:'EU', 3:'JAPAN'}, inplace=True)

print(df['origin'].unique())

int64
[1 3 2]
['USA' 'JAPAN' 'EU']


#### Q4. origin 열의 자료형을 확인하고 범주형으로 변환하여 출력하세요. --- (5점)

In [6]:
print(df['origin'].dtypes)

object


In [7]:
print('origin 열 타입 :',type(df['origin']))
dfc = df['origin'].astype('category')
display(dfc.head())

origin 열 타입 : <class 'pandas.core.series.Series'>


0    USA
1    USA
2    USA
3    USA
4    USA
Name: origin, dtype: category
Categories (3, object): [EU, JAPAN, USA]

#### Q5. origin 열을 범주형에서 문자열로 변환한 후 자료형을 출력하세요. --- (5점)

In [8]:
dfs = df['origin'].astype('object')
display(dfs.dtypes)
display(type(dfs))
display(type(dfs.dtypes))

dtype('O')

pandas.core.series.Series

numpy.dtype

#### Q6. df.horsepower를 범주형(카테고리) 데이터 처리한 후 아래와 같이 출력하세요. --- (5점)
horsepower hp_bin\
0       130.0   보통출력\
1       165.0   보통출력\
2       150.0   보통출력\
3       150.0   보통출력\
4       140.0   보통출력


In [9]:
import numpy as np

df['horsepower'].replace('?', np.nan, inplace=True)
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df['horsepower'] = df['horsepower'].astype('float') 
df['hp'] = df['horsepower'].astype('int') 

count, bin_dividers = np.histogram(df['horsepower'], bins=3) 
print(count)
# display(bin_dividers) 
print()

bin_names = ['저출력', '보통출력', '고출력']

df['hp_bin'] = pd.cut(x=df['horsepower'], bins=bin_dividers, labels=bin_names, include_lowest=True)    

display(df[['horsepower', 'hp_bin']].head())

[257 103  32]



horsepower hp_bin
0       130.0   보통출력
1       165.0   보통출력
2       150.0   보통출력
3       150.0   보통출력
4       140.0   보통출력

#### Q7. hp_bin 열의 범주형 데이터를 숫자형 범주로 변환하여 앞에서 15개만 출력하세요. --- (5점) - 틀림

In [10]:
horsepower_dummies = pd.get_dummies(df['hp_bin'])
horsepower_dummies.head(15)

저출력  보통출력  고출력
0     0     1    0
1     0     1    0
2     0     1    0
3     0     1    0
4     0     1    0
5     0     0    1
6     0     0    1
7     0     0    1
8     0     0    1
9     0     0    1
10    0     0    1
11    0     1    0
12    0     1    0
13    0     0    1
14    1     0    0

In [11]:
# 풀이
from sklearn import preprocessing    

# 전처리를 위한 encoder 객체 만들기
le = preprocessing.LabelEncoder()
result = le.fit_transform(df.hp_bin.head(15))
print(result)

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]


#### Q8. stock-data.csv를 불러와서 아래사항을 수행하세요. --- (10점)
- object 자료형으로 되어있는 Date 컬럼을 datetime64 자료형으로 변환
- new_Date 컬럼을 생성한 후 다시 인덱스로 셋팅하고 기존 Date는 삭제한 후 출력 

In [12]:
df = pd.read_csv('../stock-data.csv')
df['Date'] = pd.to_datetime(df['Date'])
display(df.info())  # datetime64 자료형으로 변환

df['new_Date'] = pd.to_datetime(df['Date'])
display(df.info()) # new_Date 컬럼 생성 확인

df.set_index('new_Date', inplace=True) # new_Date 컬럼을 인덱스로 지정
df.drop('Date', axis=1, inplace=True) # 기존 Date 컬럼 삭제
display(df.head())        # 출력

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    20 non-null     datetime64[ns]
 1   Close   20 non-null     int64         
 2   Start   20 non-null     int64         
 3   High    20 non-null     int64         
 4   Low     20 non-null     int64         
 5   Volume  20 non-null     int64         
dtypes: datetime64[ns](1), int64(5)
memory usage: 1.1 KB


None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      20 non-null     datetime64[ns]
 1   Close     20 non-null     int64         
 2   Start     20 non-null     int64         
 3   High      20 non-null     int64         
 4   Low       20 non-null     int64         
 5   Volume    20 non-null     int64         
 6   new_Date  20 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(5)
memory usage: 1.2 KB


None

Close  Start   High    Low  Volume
new_Date                                      
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

#### Q9. stock-data.csv를 불러와서 아래 사항을 수행한 후 월별 데이터를 작성하여 출력하세요. --- (10점)
- object 자료형으로 되어있는 Date 컬럼을 datetime64 자료형으로 변환하여 new_Date 컬럼을 생성
- dt 속성을 이용하여 period로 변환, 월단위 기간을 의미하는 Date_m 컬럼을 생성하고 인덱스로 지정

In [13]:
# 날짜 데이터 분리
import pandas as pd
# read_csv() 함수로 파일 읽어와서 df로 변환
df = pd.read_csv('../stock-data.csv')

# 문자열인 날짜 데이터를 판다스 Timestamp 로 변환
df['new_Date'] = pd.to_datetime(df['Date']) # df에 새로운 열로 추가

# dt 속성을 이용하여 new_Date 열의 정보를 월로 구분
df['Month'] = df['new_Date'].dt.month
display(df.head(3))

# Timestamp를 Period로 변환하여 월 표기 변경하기
df['Date_m'] = df['new_Date'].dt.to_period(freq='M')
display(df.head(3))

# 원하는 열을 새로운 행 인덱스로 지정
df.set_index('Date_m', inplace=True)
display(df.head(3))

Date  Close  Start   High    Low  Volume   new_Date  Month
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02      7
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29      6
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28      6

Date  Close  Start   High    Low  Volume   new_Date  Month   Date_m
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02      7  2018-07
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29      6  2018-06
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28      6  2018-06

Date  Close  Start   High    Low  Volume   new_Date  Month
Date_m                                                                   
2018-07  2018-07-02  10100  10850  10900  10000  137977 2018-07-02      7
2018-06  2018-06-29  10700  10550  10900   9990  170253 2018-06-29      6
2018-06  2018-06-28  10400  10900  10950  10150  155769 2018-06-28      6

#### Q10. df.mpg를 정규화 수행한 후 수행전과 후의 통계요약표를 출력하세요. --- (10점)

In [14]:
df = pd.read_csv('../auto-mpg.csv', header=None)
df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
display(df.mpg.describe()) # 정규화 수행 전 통계요약표

df.mpg = df.mpg / abs(df.mpg.max())
display(df.mpg.describe()) # 정규화 수행 후 통계요약표

count    398.000000
mean      23.514573
std        7.815984
min        9.000000
25%       17.500000
50%       23.000000
75%       29.000000
max       46.600000
Name: mpg, dtype: float64

count    398.000000
mean       0.504605
std        0.167725
min        0.193133
25%        0.375536
50%        0.493562
75%        0.622318
max        1.000000
Name: mpg, dtype: float64